datasets:
  common_voice:
    dataset_name: "cowcheng/mozilla_foundation_common_voice_corpus_20_0"
    subsets:
      cantonese:
        name: "cantonese"
        split: "data"
        num_rows: 100000
      english:
        name: "english"
        split: "data"
        num_rows: 200000
      mandarin:
        name: "mandarin"
        split: "data"
        num_rows: 100000
    audio_column: "audio"
    transcription_column: "sentence"
    test_size: 0.1

trainer:
  pretrained_model_name: "openai/whisper-tiny"
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 3.75e-5
  num_train_epochs: 9
  lr_scheduler_type: "cosine"
  warmup_steps: 650
  logging_steps: 25
  save_steps: 600
  precision: "bf16"
  eval_steps: 600
  gradient_checkpointing: true
